#include "agpch.h"

#include "test.h"

namespace Agate
{


    void helloWorld()
    {
        std::cout << "Hello World!" << std::endl;
    }


    void testworld()
    {
        //generated by vsa
    }

}// namespace Agate
