name: Build

on:
  schedule:
    - cron: "0 18 * * 5"  # Runs every Friday at 6 PM UTC
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev

    - name: Configure and build
      run: |
        mkdir build
        cd build
        cmake ..
        make

