name: Build Debug and Release

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }} - ${{ matrix.config }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        config: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install CMake on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get install -y cmake

    - name: Install CMake on Windows
      if: runner.os == 'Windows'
      run: |
        choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        refreshenv

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.config }}

    - name: Build with CMake
      run: cmake --build build --config ${{ matrix.config }}

    - name: Post build actions
      if: always()
      run: |
        echo "Build finished with ${{ matrix.config }} configuration on ${{ matrix.os }}."
