name: Build Debug and Release

on:
  schedule:
    # Run every week on Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build on ${{ matrix.os }} - ${{ matrix.config }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        config: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: actions/setup-cmake@v3
      with:
        cmake-version: '3.21.1'  # Specify the version you need

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.config }}

    - name: Build with CMake
      run: cmake --build build --config ${{ matrix.config }}

    - name: Post build actions
      if: always()
      run: |
        echo "Build finished with ${{ matrix.config }} configuration on ${{ matrix.os }}."
