name: Build Debug and Release

on:
  schedule:
    - cron: '0 18 * * 5' # Runs every Friday at 6 PM UTC
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build on ${{ matrix.os }} - ${{ matrix.config }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        config: [Debug, Release]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: true          # Checkout submodules
        fetch-depth: 0            # Ensure the full history is fetched

    - name: Install dependencies on Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev libxkbcommon-dev

    - name: Install CMake on Windows
      if: runner.os == 'Windows'
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.config }}

    - name: Build with CMake
      run: cmake --build build --config ${{ matrix.config }}

    - name: Post build actions
      if: always()
      run: |
        echo "Build finished with ${{ matrix.config }} configuration on ${{ matrix.os }}."
